GET  https://student.cloud.htl-leonding.ac.at/d.pavelescu/rasa/webhooks/web/

###

POST https://student.cloud.htl-leonding.ac.at/d.pavelescu/rasa/webhooks/web/webhook HTTP/1.1
Host: student.cloud.htl-leonding.ac.at
Content-Type: application/json
Content-Length: 72

{
    "sender": "someuser",
    "text":"hello",
    "metadata": {}
}

###